### PR TITLE
Grab Sprint image captions

### PR DESCRIPTION
**Pull request by jpmcgrath**
Hi Mike,

This proved to be a little more complex than I initially thought as Sprint uses Ajax to serve up JSON that is then turned into html content. The changes I have made work out the URL to download the JSON from. Then it extract any text content to create text/html media for the mms mail object. 

Also worth noting is that to parse the JSON response I have included the JSON gem in the gemfile. Hope this is ok.

I was thinking about writing a test case for these changes, but I'm not sure how to achieve it as it would require a persistent MMS message stored on the Sprint servers. Because they expire any message after 60 days, any test that i can think of would expire with the message. If you have thoughts on this let me know.

Cheers,

James.

### CODE REVIEW

**Comment by monde** [comment]
James can you provide some tests?  This implementation breaks the current test suite for sprint.  Here is my output:

https://gist.github.com/2468933

I'm tracking your changes in my sprint_json branch:

https://github.com/monde/mms2r/tree/sprint_json

I would like to try out your work on my live application that gave birth to MMS2R before releasing a new version.  However, I'm leary of doing so until I have all the tests passing.

I really appreciate your help and feedback with MMS2R and I am looking forward to trying your work out in a production environment!

**Comment by jpmcgrath** [comment]
Hi Mike, I'm back! Sorry for the silence. I got snowed under with my day job and before I knew it a month had gone by!

I have spend a bit of time understanding the test cases and have created some of my own for the "sprint get text message content from ajax" functionality I added in my last pull request.

I have also put in a bit more error checking to test for the following:
1. check that the "view entire message" link exists before continuing
2. check that the response from the server is successfully parsed as JSON. If not, catch the error and assume the content has expired and been purged by sprint.

Please check these test out thoroughly to make sure that you are happy that I provided enough coverage. If there are any improvements you'd like please let me know.

Cheers.

**Comment by monde** [comment]
This is great.  I'll to get a look at it by this next evening, I've been crushed by work and family commitments lately.

**Comment by jpmcgrath** [comment]
You and me both. Thanks Mike.
On May 30, 2012 6:03 AM, "Mike Mondragon" <
reply@reply.github.com>
wrote:

**Comment by jpmcgrath** [comment]
Hi Mike,

have you had a chance to look at those tests I wrote? I'm pretty keen
to see my changes into master, so please let me know if there is
anything I can do on my end.

Cheers,

James.

p.s: I completely understand that mms2r is a labor of love and such
things often take a back seat to more immediate/pressing priorities,
so please don't feel pressured by this email, it's just meant to be a
friendly nudge!

**Comment by monde** [comment]
You are in, thanks for working that out!  I updated the gem as well and released version 3.7.0

**Comment by jpmcgrath** [comment]
Awesome, thanks Mike!

**Comment by jpmcgrath** [comment]
Thought you might like to know that the linebreaks seem to be missing from the in gem description on Rubygems.org (http://rubygems.org/gems/mms2r)

**Pull request merged**
